name: mentra
description: A mental health and wellness app

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  firebase_core: ^2.18.0
  cloud_firestore: ^4.15.1
  firebase_auth: ^4.11.1
  firebase_storage: ^11.7.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pedometer: ^4.0.0
  flutter_local_notifications: ^13.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  sensors_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  